#include <string.h>

#include "mufprims.h"


struct funcinfo_t prims_list[] = {
    /* Name                Code               args rtns vararg */
    { "throw",             "abort",             1,  0,  0},
    { "abort",             "abort",             1,  0,  0},

    { "awake?",            "awake?",            1,  1,  0},
    { "online",            "online_array",      0,  1,  0},
    { "online_array",      "online_array",      0,  1,  0},

    { "conboot",           "conboot",           1,  1,  0},
    { "concount",          "concount",          0,  1,  0},
    { "condbref",          "condbref",          1,  1,  0},
    { "condescr",          "condescr",          1,  1,  0},
    { "conhost",           "conhost",           1,  1,  0},
    { "conidle",           "conidle",           1,  1,  0},
    { "connotify",         "connotify",         2,  0,  0},
    { "contime",           "contime",           1,  1,  0},
    { "conuser",           "conuser",           1,  1,  0},

    { "descr",             "descr",             0,  1,  0},
    { "descr_array",       "descr_array",       1,  1,  0},
    { "descr_setuser",     "descr_setuser",     3,  1,  0},
    { "descrboot",         "descrboot",         1,  1,  0},
    { "descrbufsize",      "descrbufsize",      1,  1,  0},
    { "descrcon",          "descrcon",          1,  1,  0},
    { "descrdbref",        "descrdbref",        1,  1,  0},
    { "descrflush",        "descrflush",        1,  0,  0},
    { "descrhost",         "descrhost",         1,  1,  0},
    { "descridle",         "descridle",         1,  1,  0},
    { "descriptors",       "descriptors array_make",  1,  1,  0},
    { "descrleastidle",    "descrleastidle",    1,  1,  0},
    { "descrmostidle",     "descrmostidle",     1,  1,  0},
    { "descrnotify",       "descrnotify",       2,  0,  0},
    { "descrsecure?",      "descrsecure?",      1,  1,  0},
    { "descrtime",         "descrtime",         1,  1,  0},
    { "descruser",         "descruser",         1,  1,  0},
    { "firstdescr",        "firstdescr",        1,  1,  0},
    { "lastdescr",         "lastdescr",         1,  1,  0},
    { "nextdescr",         "nextdescr",         1,  1,  0},

    { "call",              "call",              1, 99,  0},
    { "call_public",       "call",              2, 99,  0},
    { "cancall",           "cancall?",          2,  1,  0},
    { "interp",            "interp",            3,  1,  0},

    { "event_count",       "event_count",       0,  1,  0},
    { "event_exists",      "event_exists",      1,  1,  0},
    { "event_wait",        "event_wait",        0,  2,  0},
    { "event_waitfor",     "event_waitfor",     1,  2,  0},
    { "event_send",        "event_send",        3,  0,  0},
    { "timer_start",       "timer_start",       2,  0,  0},
    { "timer_stop",        "timer_stop",        1,  0,  0},
    { "watchpid",          "watchpid",          1,  0,  0},

    { "tell",              "me @ swap notify",  1,  0,  0},
    { "notify",            "notify",            2,  0,  0},
    { "notify_except",     "notify_except",     3,  0,  0},
    { "notify_exclude", "swap array_explode dup 2 + rotate notify_exclude",  3,  0,  0},
    { "array_notify",      "array_notify",      2,  0,  0},
    { "user_log",          "user_log",          1,  0,  0},
    { "read",              "read",              0,  1,  0},
    { "tread",             "tread",             1,  2,  0},
    { "read_wants_blanks", "read_wants_blanks", 0,  0,  0},

    { "atoi",              "atoi",              1,  1,  0},
    { "ctoi",              "ctoi",              1,  1,  0},
    { "int",               "int",               1,  1,  0},
    { "intostr",           "intostr",           1,  1,  0},
    { "itoc",              "itoc",              1,  1,  0},
    { "stod",              "stod",              1,  1,  0},
    { "dbref",             "dbref",             1,  1,  0},

    { "prog",              "prog",              0,  1,  0},
    { "trig",              "trig",              0,  1,  0},
    { "caller",            "caller",            0,  1,  0},

    { "address?",          "address?",          1,  1,  0},
    { "array?",            "array?",            1,  1,  0},
    { "dbref?",            "dbref?",            1,  1,  0},
    { "dictionary?",       "dictionary?",       1,  1,  0},
    { "float?",            "float?",            1,  1,  0},
    { "int?",              "int?",              1,  1,  0},
    { "lock?",             "lock?",             1,  1,  0},
    { "number?",           "number?",           1,  1,  0},
    { "string?",           "string?",           1,  1,  0},

    { "explode",           "explode_array",     2,  1,  0},
    { "explode_array",     "explode_array",     2,  1,  0},
    { "instr",             "instr",             2,  1,  0},
    { "instring",          "instring",          2,  1,  0},
    { "midstr",            "midstr",            3,  1,  0},
    { "rinstr",            "rinstr",            2,  1,  0},
    { "rinstring",         "rinstring",         2,  1,  0},
    { "rsplit",            "rsplit",            2,  2,  0},
    { "smatch",            "smatch",            2,  1,  0},
    { "split",             "split",             2,  2,  0},
    { "strcat",            "strcat",            2,  1,  0},
    { "strcmp",            "strcmp",            2,  1,  0},
    { "strcut",            "strcut",            2,  2,  0},
    { "stringcmp",         "stringcmp",         2,  1,  0},
    { "stringpfx",         "stringpfx",         2,  1,  0},
    { "strip",             "strip",             1,  1,  0},
    { "striplead",         "striplead",         1,  1,  0},
    { "striptail",         "striptail",         1,  1,  0},
    { "strlen",            "strlen",            1,  1,  0},
    { "strmatch",          "strmatch",          2,  1,  0},
    { "strncmp",           "strncmp",           3,  1,  0},
    { "subst",             "subst",             3,  1,  0},
    { "tolower",           "tolower",           1,  1,  0},
    { "toupper",           "toupper",           1,  1,  0},

    { "strencrypt",        "strencrypt",        2,  1,  0},
    { "strdecrypt",        "strdecrypt",        2,  1,  0},

    { "regexp",            "regexp",            3,  2,  0},
    { "regsub",            "regsub",            4,  1,  0},

    { "locked?",           "locked?",           2,  1,  0},
    { "parselock",         "parselock",         1,  1,  0},
    { "unparselock",       "unparselock",       1,  1,  0},
    { "prettylock",        "prettylock",        1,  1,  0},
    { "testlock",          "testlock",          2,  1,  0},
    { "setlockstr",        "setlockstr",        2,  1,  0},
    { "getlockstr",        "getlockstr",        1,  1,  0},

    { "array_fmtstrings",  "array_fmtstrings",  2,  1,  0},
    { "pronoun_sub",       "pronoun_sub",       2,  1,  0},
    { "tokensplit",        "tokensplit",        3,  3,  0},

    { "textattr",          "textattr",          2,  1,  0},
    { "ansi_strip",        "ansi_strip",        1,  1,  0},
    { "ansi_strlen",       "ansi_strlen",       1,  1,  0},
    { "ansi_strcut",       "ansi_strcut",       2,  2,  0},
    { "ansi_midstr",       "ansi_midstr",       3,  1,  0},

    { "getseed",           "getseed",           0,  1,  0},
    { "setseed",           "setseed",           1,  0,  0},
    { "srand",             "srand",             0,  1,  0},
    { "frand",             "frand",             0,  1,  0},
    { "random",            "random",            0,  1,  0},
    { "gaussian",          "gaussian",          2,  1,  0},

    { "abs",               "abs",               1,  1,  0},
    { "ceil",              "ceil",              1,  1,  0},
    { "floor",             "floor",             1,  1,  0},
    { "fmod",              "fmod",              2,  1,  0},
    { "modf",              "modf",              1,  2,  0},
    { "sign",              "sign",              1,  1,  0},

    { "sqrt",              "sqrt",              1,  1,  0},
    { "pow",               "pow",               2,  1,  0},
    { "log",               "log",               1,  1,  0},
    { "exp",               "exp",               1,  1,  0},
    { "log10",             "log10",             1,  1,  0},
    { "exp10",             "exp10",             1,  1,  0},

    { "sin",               "sin",               1,  1,  0},
    { "cos",               "cos",               1,  1,  0},
    { "tan",               "tan",               1,  1,  0},
    { "asin",              "asin",              1,  1,  0},
    { "acos",              "acos",              1,  1,  0},
    { "atan",              "atan",              1,  1,  0},
    { "atan2",             "atan2",             2,  1,  0},

    { "diff3",             "diff3",             6,  3,  0},
    { "dist3d",            "dist3d",            3,  1,  0},
    { "xyz_to_polar",      "xyz_to_polar",      3,  3,  0},
    { "polar_to_xyz",      "polar_to_xyz",      3,  3,  0},

    { "clear",             "clear",             0,  0,  0},
    { "clear_error",       "clear_error",       1,  1,  0},
    { "error?",            "error?",            0,  1,  0},
    { "error_bit",         "error_bit",         1,  1,  0},
    { "error_name",        "error_name",        1,  1,  0},
    { "error_num",         "error_num",         0,  1,  0},
    { "error_str",         "error_str",         1,  1,  0},
    { "is_set?",           "is_set?",           1,  1,  0},
    { "set_error",         "set_error",         1,  1,  0},

    { "array_keys",        "array_keys array_make",  2,  1,  0},
    { "array_vals",        "array_vals array_make",  2,  1,  0},

    { "array_appenditem",   "array_appenditem",   2,  1,  0},
    { "array_compare",      "array_compare",      2,  1,  0},
    { "array_cut",          "array_cut",          2,  2,  0},
    { "array_delitem",      "array_delitem",      2,  1,  0},
    { "array_delrange",     "array_delrange",     3,  1,  0},
    { "array_diff",         "array_diff",         2,  1,  0},
    { "array_excludeval",   "array_excludeval",   2,  1,  0},
    { "array_extract",      "array_extract",      2,  1,  0},
    { "array_findval",      "array_findval",      2,  1,  0},
    { "array_first",        "array_first",        1,  2,  0},
    { "array_getrange",     "array_getrange",     2,  1,  0},
    { "array_insertitem",   "array_insertitem",   3,  1,  0},
    { "array_insertrange",  "array_insertrange",  3,  1,  0},
    { "array_interpret",    "array_interpret",    1,  1,  0},
    { "array_intersect",    "array_intersect",    2,  1,  0},
    { "array_join",         "array_join",         2,  1,  0},
    { "array_last",         "array_last",         1,  2,  0},
    { "array_matchkey",     "array_matchkey",     2,  1,  0},
    { "array_matchval",     "array_matchval",     2,  1,  0},
    { "array_nested_del",   "array_nested_del",   2,  1,  0},
    { "array_nested_get",   "array_nested_get",   2,  1,  0},
    { "array_nested_set",   "array_nested_set",   3,  1,  0},
    { "array_next",         "array_next",         2,  2,  0},
    { "array_prev",         "array_prev",         2,  2,  0},
    { "array_reverse",      "array_reverse",      1,  1,  0},
    { "array_setrange",     "array_setrange",     3,  1,  0},
    { "array_sort",         "array_sort",         2,  1,  0},
    { "array_sort_indexed", "array_sort_indexed", 3,  1,  0},
    { "array_union",        "array_union",        2,  1,  0},

    { "dbtop",             "dbtop",             0,  1,  0},
    { "dbcmp",             "dbcmp",             2,  1,  0},
    { "unparseobj",        "unparseobj",        1,  1,  0},
    { "owner",             "owner",             1,  1,  0},
    { "setown",            "setown",            2,  0,  0},
    { "location",          "location",          1,  1,  0},
    { "moveto",            "moveto",            2,  0,  0},
    { "contents",          "contents",          1,  1,  0},
    { "contents_array",    "contents_array",    1,  1,  0},
    { "exits",             "exits",             1,  1,  0},
    { "exits_array",       "exits_array",       1,  1,  0},
    { "next",              "next",              1,  1,  0},
    { "nextowned",         "nextowned",         1,  1,  0},
    { "findnext",          "findnext",          4,  1,  0},
    { "nextentrance",      "nextentrance",      2,  1,  0},
    { "controls",          "controls",          2,  1,  0},

    { "copyobj",           "copyobj",           1,  1,  0},
    { "copyplayer",        "copyplayer",        3,  1,  0},
    { "toadplayer",        "toadplayer",        2,  0,  0},
    { "newplayer",         "newplayer",         2,  1,  0},
    { "newroom",           "newroom",           2,  1,  0},
    { "newobject",         "newobject",         2,  1,  0},
    { "newexit",           "newexit",           2,  1,  0},
    { "newprogram",        "newprogram",        2,  1,  0},
    { "recycle",           "recycle",           1,  0,  0},

    { "ignoring?",         "ignoring?",         2,  1,  0},
    { "ignore_add",        "ignore_add",        2,  0,  0},
    { "ignore_del",        "ignore_del",        2,  0,  0},
    { "array_get_ignorelist", "array_get_ignorelist", 1, 1, 0},

    { "match",             "match",             1,  1,  0},
    { "rmatch",            "rmatch",            2,  1,  0},
    { "pmatch",            "pmatch",            1,  1,  0},
    { "part_pmatch",       "part_pmatch",       1,  1,  0},

    { "name_ok?",          "name-ok?",          1,  1,  0},
    { "pname_ok?",         "pname-ok?",         1,  1,  0},
    { "ext_name_ok?",      "ext-name-ok?",      2,  1,  0},

    { "pennies",           "pennies",           1,  1,  0},
    { "addpennies",        "addpennies",        2,  0,  0},
    { "movepennies",       "movepennies",       3,  0,  0},

    { "checkpassword",     "checkpassword",     2,  1,  0},
    { "newpassword",       "newpassword",       2,  0,  0},
    { "set",               "set",               2,  0,  0},
    { "flag?",             "flag?",             2,  1,  0},
    { "mlevel",            "mlevel",            1,  1,  0},

    { "ok?",               "ok?",               1,  1,  0},
    { "player?",           "player?",           1,  1,  0},
    { "room?",             "room?",             1,  1,  0},
    { "thing?",            "thing?",            1,  1,  0},
    { "exit?",             "exit?",             1,  1,  0},
    { "program?",          "program?",          1,  1,  0},

    { "sysparm",           "sysparm",           1,  1,  0},
    { "sysparm_array",     "sysparm_array",     1,  1,  0},
    { "setsysparm",        "setsysparm",        2,  0,  0},

    { "desc",              "desc",              1,  1,  0},
    { "drop",              "drop",              1,  1,  0},
    { "fail",              "fail",              1,  1,  0},
    { "name",              "name",              1,  1,  0},
    { "odrop",             "odrop",             1,  1,  0},
    { "ofail",             "ofail",             1,  1,  0},
    { "osucc",             "osucc",             1,  1,  0},
    { "setdesc",           "setdesc",           2,  0,  0},
    { "setdrop",           "setdrop",           2,  0,  0},
    { "setfail",           "setfail",           2,  0,  0},
    { "setname",           "setname",           2,  0,  0},
    { "setodrop",          "setodrop",          2,  0,  0},
    { "setofail",          "setofail",          2,  0,  0},
    { "setosucc",          "setosucc",          2,  0,  0},
    { "setsucc",           "setsucc",           2,  0,  0},
    { "succ",              "succ",              1,  1,  0},
    { "truename",          "truename",          1,  1,  0},

    { "getlink",           "getlink",           1,  1,  0},
    { "setlink",           "setlink",           2,  0,  0},
    { "getlinks",          "getlinks array_make",  1,  1,  0},
    { "getlinks_array",    "getlinks_array",    1,  1,  0},
    { "setlinks_array",    "setlinks_array",    2,  0,  0},
    { "entrances_array",   "entrances_array",   1,  1,  0},
    { "timestamps",        "timestamps",        1,  4,  0},
    { "timestamps",        "timestamps",        1,  4,  0},
    { "stats",             "stats",             1,  7,  0},
    { "objmem",            "objmem",            1,  1,  0},

    { "addprop",            "addprop",            4,  0,  0},
    { "array_filter_flags", "array_filter_flags", 2,  1,  0},
    { "array_filter_prop",  "array_filter_prop",  3,  1,  0},
    { "array_get_propdirs", "array_get_propdirs", 2,  1,  0},
    { "array_get_proplist", "array_get_proplist", 2,  1,  0},
    { "array_get_propvals", "array_get_propvals", 2,  1,  0},
    { "array_get_reflist",  "array_get_reflist",  2,  1,  0},
    { "array_put_proplist", "array_put_proplist", 3,  0,  0},
    { "array_put_propvals", "array_put_propvals", 3,  0,  0},
    { "array_put_reflist",  "array_put_reflist",  3,  0,  0},
    { "blessprop",          "blessprop",          2,  0,  0},
    { "envprop",            "envprop",            2,  2,  0},
    { "envpropstr",         "envpropstr",         2,  2,  0},
    { "getprop",            "getprop",            2,  1,  0},
    { "getpropfval",        "getpropfval",        2,  1,  0},
    { "getpropstr",         "getpropstr",         2,  1,  0},
    { "getpropval",         "getpropval",         2,  1,  0},
    { "blessed?",           "blessed?",           2,  1,  0},
    { "propdir?",           "propdir?",           2,  1,  0},
    { "nextprop",           "nextprop",           2,  1,  0},
    { "parseprop",          "parseprop",          4,  1,  0},
    { "parsepropex",        "parsepropex",        4,  2,  0},
    { "reflist_add",        "reflist_add",        3,  0,  0},
    { "reflist_del",        "reflist_del",        3,  0,  0},
    { "reflist_find",       "reflist_find",       3,  1,  0},
    { "reflist_get",        "array_get_reflist",  2,  1,  0},
    { "reflist_put",        "array_put_reflist",  3,  0,  0},
    { "remove_prop",        "remove_prop",        2,  0,  0},
    { "setprop",            "setprop",            3,  0,  0},
    { "unblessprop",        "unblessprop",        2,  0,  0},

    { "time",               "time",               0,  3,  0},
    { "date",               "date",               0,  3,  0},
    { "datetime",           "time date",          0,  6,  0},
    { "systime",            "systime",            0,  1,  0},
    { "systime_precise",    "systime_precise",    0,  1,  0},
    { "gmtoffset",          "gmtoffset",          0,  1,  0},
    { "timesplit",          "timesplit",          1,  8,  0},
    { "timefmt",            "timefmt",            2,  1,  0},
    { "sleep",              "sleep",              1,  0,  0},

    { "mode",               "mode",               0,  1,  0},
    { "setmode",            "setmode",            1,  0,  0},
    { "preempt",            "preempt",            0,  0,  0},
    { "foreground",         "foreground",         0,  0,  0},
    { "background",         "background",         0,  0,  0},
    { "queue",              "queue",              3,  1,  0},
    { "fork",               "fork",               0,  1,  0},
    { "kill",               "kill",               1,  1,  0},
    { "pid",                "pid",                0,  1,  0},
    { "ispid?",             "ispid?",             1,  1,  0},
    { "getpids",            "getpids",            1,  1,  0},
    { "getpidinfo",         "getpidinfo",         1,  1,  0},
    { "instances",          "instances",          1,  1,  0},
    { "compile",            "compile",            2,  1,  0},
    { "uncompile",          "uncompile",          1,  0,  0},
    { "compiled?",          "compiled?",          1,  1,  0},
    { "program_getlines",   "program_getlines",   3,  1,  0},
    { "program_setlines",   "program_setlines",   2,  0,  0},

    { "mcp_register",       "mcp_register",       3,  0,  0},
    { "mcp_register_event", "mcp_register_event", 3,  0,  0},
    { "mcp_bind",           "mcp_bind",           3,  0,  0},
    { "mcp_supports",       "mcp_supports",       2,  1,  0},
    { "mcp_send",           "mcp_send",           4,  0,  0},

    { "gui_available",      "gui_available",      1,  1,  0},
    { "gui_dlog_create",    "gui_dlog_create",    4,  1,  0},
    { "gui_dlog_simple",    "gui_dlog_simple",    2,  1,  0},
    { "gui_dlog_helper",    "gui_dlog_helper",    3,  1,  0},
    { "gui_dlog_show",      "gui_dlog_show",      1,  0,  0},
    { "gui_dlog_close",     "gui_dlog_close",     1,  0,  0},
    { "gui_ctrl_create",    "gui_ctrl_create",    4,  0,  0},
    { "gui_ctrl_command",   "gui_ctrl_command",   4,  0,  0},
    { "gui_values_get",     "gui_values_get",     1,  1,  0},
    { "gui_value_get",      "gui_value_get",      2,  1,  0},
    { "gui_value_set",      "gui_value_set",      3,  0,  0},

    { "debug_on",           "debug_on",           0,  0,  0},
    { "debug_off",          "debug_off",          0,  0,  0},
    { "debug_line",         "debug_line",         0,  0,  0},
    { "debugger_break",     "debugger_break",     0,  0,  0},

    { "version",            "version",            0,  1,  0},
    { "force",              "force",              2,  0,  0},
    { "force_level",        "force_level",        0,  1,  0},

    {0, 0, 0, 0, 0}
};


struct funcinfo_t *
funclookup(const char*s)
{
    int i;
    for (i = 0; prims_list[i].name; i++) {
        if (!strcmp(prims_list[i].name, s)) {
            return &prims_list[i];
        }
    }
    return NULL;
}


/* vim: set ts=4 sw=4 et ai hlsearch nowrap : */
